include:
  - node_modules/leaflet/dist/leaflet.css
  - node_modules/leaflet/dist/leaflet.js
  - node_modules/jquery/dist/jquery.min.js
  - node_modules/bootstrap-css-only/css/bootstrap.min.css
  - node_modules/bootstrap-css-only/css/bootstrap-responsive.min.css
  - node_modules/leaflet.markercluster/dist/leaflet.markercluster.js
  - node_modules/leaflet.markercluster/dist/MarkerCluster.css
  - node_modules/leaflet.markercluster/dist/MarkerCluster.Default.css
  - node_modules/esri-leaflet/dist/esri-leaflet.js
  - node_modules/leaflet-geosearch/src/js/l.geosearch.provider.esri.js
  - node_modules/leaflet-geosearch/src/js/l.control.geosearch.js
  - node_modules/leaflet-geosearch/src/css/l.geosearch.css
  - node_modules/leaflet-geosearch/src/img/geosearch.png
  - node_modules/leaflet-geosearch/src/js/l.geosearch.provider.google.js
  - node_modules/handlebars/dist/handlebars.min.js
  - node_modules/tabletop/src/tabletop.js
  - node_modules/moment/min/moment.min.js

exclude:
  - package.json
  - package-lock.json
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - OLD_CNAME
  